#!/bin/bash

# Builds a docker image with all runtime dependencies
# and runs the specified script using PyPy.

set -e

IMAGE=pyclick
WORKING_DIR=/usr/src/myapp

if ! type "docker" > /dev/null; then
    echo 
    echo "Please install Docker to use this script! https://www.docker.com/"
    exit 1
fi

function rebuild {
    docker build --no-cache -t $IMAGE $(dirname $0)
}

if [[ "$1" = "rebuild" ]] ; then
    rebuild
    exit 0
fi

if [[ -z $(docker images | grep $IMAGE) ]] ; then
    rebuild
    echo
fi

docker run \
    --interactive \
    --tty=true \
    --volume=$(pwd):$WORKING_DIR \
    --workdir $WORKING_DIR \
    $IMAGE pypy $@

